import {Platform} from 'react-native';
import {toPng} from 'html-to-image';
import {
  photoService,
  PhotoCategory,
  isAutoGeneratedPhotoCategory,
} from './photoService';

export interface LdrDocumentPhotoInput {
  orderNumber: string;
  trackingNumber: string;
  customerName?: string;
  technicianName?: string;
  signatureDataUri?: string | null;
  wasteCodes?: string[];
  dateLabel?: string;
}

export interface NoShipDocumentPhotoInput {
  orderNumber: string;
  storeNumber: string;
  storeAddress: string;
  serviceDate: string;
  sections: Array<'pharmacy' | 'retail' | 'sump' | 'fuel'>;
  technicianName?: string;
  signatureDataUri?: string | null;
  printedNames?: Partial<
    Record<'pharmacy' | 'retail' | 'sump' | 'fuel' | 'technician', string>
  >;
  signatures?: Partial<
    Record<'pharmacy' | 'retail' | 'sump' | 'fuel' | 'technician', string | null>
  >;
  /** When provided (e.g. captured sheet screenshot), used instead of drawing. */
  documentUri?: string | null;
}

const AUTO_CATEGORIES: PhotoCategory[] = ['ldr', 'no-ship'];

/**
 * Captures a rendered React Native Web View/DOM node as a PNG data URI.
 * Returns null on native or when capture fails (caller should fall back).
 */
export async function captureElementAsDataUri(
  element: unknown,
): Promise<string | null> {
  if (Platform.OS !== 'web' || !element || typeof document === 'undefined') {
    return null;
  }

  const node = element as HTMLElement;
  if (typeof node.getBoundingClientRect !== 'function') {
    return null;
  }

  try {
    // Wait a frame so layout/paint settle (signatures, inputs, images).
    await new Promise<void>(resolve => {
      requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
    });

    const dataUrl = await toPng(node, {
      cacheBust: true,
      pixelRatio: 2,
      backgroundColor: '#ffffff',
      style: {
        // Avoid capturing scroll containers clipping the sheet.
        transform: 'none',
      },
      onClone: (_documentClone, clonedNode) => {
        // Ensure typed TextInput values appear in the screenshot.
        const sourceInputs = node.querySelectorAll('input, textarea');
        const cloneInputs = clonedNode.querySelectorAll('input, textarea');
        sourceInputs.forEach((source, index) => {
          const clone = cloneInputs[index] as
            | HTMLInputElement
            | HTMLTextAreaElement
            | undefined;
          if (!clone) return;
          const value = (source as HTMLInputElement | HTMLTextAreaElement).value;
          clone.setAttribute('value', value);
          if ('value' in clone) {
            clone.value = value;
          }
          if (value && clone.placeholder) {
            clone.placeholder = '';
          }
        });
      },
    });
    return dataUrl || null;
  } catch (error) {
    console.warn('[autoGeneratedDocumentPhotos] Failed to capture element', error);
    return null;
  }
}

function createCanvas(width: number, height: number): HTMLCanvasElement | null {
  if (typeof document === 'undefined') {
    return null;
  }
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  return canvas;
}

function wrapText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): number {
  const words = text.split(/\s+/);
  let line = '';
  let cursorY = y;
  for (let i = 0; i < words.length; i++) {
    const testLine = line ? `${line} ${words[i]}` : words[i];
    if (ctx.measureText(testLine).width > maxWidth && line) {
      ctx.fillText(line, x, cursorY);
      line = words[i];
      cursorY += lineHeight;
    } else {
      line = testLine;
    }
  }
  if (line) {
    ctx.fillText(line, x, cursorY);
    cursorY += lineHeight;
  }
  return cursorY;
}

async function drawSignature(
  ctx: CanvasRenderingContext2D,
  dataUri: string | null | undefined,
  x: number,
  y: number,
  width: number,
  height: number,
): Promise<void> {
  if (!dataUri || typeof Image === 'undefined') {
    return;
  }
  await new Promise<void>(resolve => {
    const img = new Image();
    img.onload = () => {
      ctx.drawImage(img, x, y, width, height);
      resolve();
    };
    img.onerror = () => resolve();
    img.src = dataUri;
  });
}

function fallbackDocumentDataUri(title: string, lines: string[]): string {
  // Minimal SVG wrapped as data URI — RN web Image can often render SVG data URIs;
  // for native we still prefer canvas when available.
  const escapedTitle = title.replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const textRows = lines
    .map(
      (line, index) =>
        `<text x="40" y="${120 + index * 28}" font-size="18" fill="#333">${line
          .replace(/&/g, '&amp;')
          .replace(/</g, '&lt;')}</text>`,
    )
    .join('');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="1100">
    <rect width="100%" height="100%" fill="#ffffff"/>
    <rect x="24" y="24" width="752" height="1052" fill="none" stroke="#111" stroke-width="2"/>
    <text x="40" y="70" font-size="28" font-weight="700" fill="#111">${escapedTitle}</text>
    <text x="40" y="98" font-size="14" fill="#666">Auto-generated document</text>
    ${textRows}
  </svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

async function renderLdrDataUri(input: LdrDocumentPhotoInput): Promise<string> {
  const width = 800;
  const height = 1100;
  const canvas = createCanvas(width, height);
  const codes =
    input.wasteCodes && input.wasteCodes.length > 0
      ? input.wasteCodes
      : ['—'];
  const dateLabel =
    input.dateLabel ||
    new Date().toLocaleDateString(undefined, {
      month: 'numeric',
      day: 'numeric',
      year: 'numeric',
    });

  if (!canvas) {
    return fallbackDocumentDataUri('LAND DISPOSAL RESTRICTIONS (LDR)', [
      `Manifest Tracking #: ${input.trackingNumber}`,
      `Date: ${dateLabel}`,
      `Authorized: ${input.customerName?.trim() || '—'}`,
      `Technician: ${input.technicianName || '—'}`,
      `Waste codes: ${codes.join(', ')}`,
    ]);
  }

  const ctx = canvas.getContext('2d');
  if (!ctx) {
    return fallbackDocumentDataUri('LAND DISPOSAL RESTRICTIONS (LDR)', [
      `Manifest Tracking #: ${input.trackingNumber}`,
    ]);
  }

  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, width, height);
  ctx.strokeStyle = '#111111';
  ctx.lineWidth = 2;
  ctx.strokeRect(24, 24, width - 48, height - 48);

  ctx.fillStyle = '#111111';
  ctx.font = 'bold 28px sans-serif';
  ctx.fillText('LAND DISPOSAL RESTRICTIONS (LDR)', 48, 80);
  ctx.font = '16px sans-serif';
  ctx.fillStyle = '#555555';
  ctx.fillText('Notification / Certification — 40 CFR 268.7', 48, 108);

  ctx.fillStyle = '#111111';
  ctx.font = 'bold 16px sans-serif';
  ctx.fillText('Manifest Tracking #', 48, 160);
  ctx.fillText('Date', 420, 160);
  ctx.font = '18px sans-serif';
  ctx.fillText(input.trackingNumber || '—', 48, 188);
  ctx.fillText(dateLabel, 420, 188);

  ctx.font = 'bold 16px sans-serif';
  ctx.fillText('Restricted Waste Codes', 48, 240);
  ctx.font = '16px sans-serif';
  let y = 270;
  codes.forEach(code => {
    ctx.fillText(`• ${code} — Meets 40 CFR 268.40 treatment standards`, 48, y);
    y += 28;
  });

  ctx.font = '15px sans-serif';
  y = wrapText(
    ctx,
    'I certify under penalty of law that I personally have examined and am familiar with the waste through analysis and testing or through knowledge of the waste to support this certification that the waste complies with the treatment standards specified in 40 CFR Part 268 Subpart D.',
    48,
    y + 24,
    width - 96,
    22,
  );

  ctx.font = 'bold 16px sans-serif';
  ctx.fillText('Authorized Signature', 48, y + 48);
  ctx.fillText('Printed Name / Date', 420, y + 48);
  ctx.strokeStyle = '#333333';
  ctx.beginPath();
  ctx.moveTo(48, y + 110);
  ctx.lineTo(340, y + 110);
  ctx.moveTo(420, y + 110);
  ctx.lineTo(720, y + 110);
  ctx.stroke();

  await drawSignature(ctx, input.signatureDataUri, 48, y + 52, 280, 54);
  ctx.fillStyle = '#111111';
  ctx.font = '16px sans-serif';
  ctx.fillText(input.customerName?.trim() || '', 420, y + 100);
  if (input.technicianName) {
    ctx.fillText(`Technician: ${input.technicianName}`, 48, y + 150);
  }

  ctx.fillStyle = '#888888';
  ctx.font = '12px sans-serif';
  ctx.fillText(
    'Auto-generated when manifest is created',
    48,
    height - 48,
  );

  return canvas.toDataURL('image/png');
}

async function renderNoShipDataUri(
  input: NoShipDocumentPhotoInput,
): Promise<string> {
  if (input.documentUri) {
    return input.documentUri;
  }

  const width = 900;
  const height = 1400;
  const canvas = createCanvas(width, height);
  const sectionLabels = {
    pharmacy: 'Pharmacy',
    retail: 'Retail / Front Store',
    sump: 'Sump',
    fuel: 'Fuel Center',
  } as const;
  const printed = input.printedNames ?? {};
  const sigs = input.signatures ?? {};

  if (!canvas) {
    return fallbackDocumentDataUri('No Ship Record', [
      `Order: ${input.orderNumber}`,
      `Store: ${input.storeNumber}`,
      `Address: ${input.storeAddress}`,
      `Service Date: ${input.serviceDate}`,
      `Sections: ${input.sections.map(s => sectionLabels[s]).join(', ') || '—'}`,
      `Technician: ${printed.technician || input.technicianName || '—'}`,
    ]);
  }

  const ctx = canvas.getContext('2d');
  if (!ctx) {
    return fallbackDocumentDataUri('No Ship Record', [
      `Order: ${input.orderNumber}`,
    ]);
  }

  const drawCheck = (checked: boolean, x: number, y: number) => {
    ctx.strokeStyle = '#111111';
    ctx.strokeRect(x, y - 12, 14, 14);
    if (checked) {
      ctx.beginPath();
      ctx.moveTo(x + 3, y - 5);
      ctx.lineTo(x + 6, y - 2);
      ctx.lineTo(x + 11, y - 10);
      ctx.stroke();
    }
  };

  const drawSignaturePair = async (
    labelLeft: string,
    labelRight: string,
    printedName: string | undefined,
    signatureUri: string | null | undefined,
    startY: number,
  ): Promise<number> => {
    ctx.fillStyle = '#555555';
    ctx.font = '12px sans-serif';
    ctx.fillText(labelLeft, 48, startY);
    ctx.fillText(labelRight, 480, startY);
    ctx.strokeStyle = '#333333';
    ctx.beginPath();
    ctx.moveTo(48, startY + 48);
    ctx.lineTo(400, startY + 48);
    ctx.moveTo(480, startY + 48);
    ctx.lineTo(852, startY + 48);
    ctx.stroke();
    await drawSignature(ctx, signatureUri, 480, startY + 4, 360, 42);
    ctx.fillStyle = '#111111';
    ctx.font = '16px sans-serif';
    ctx.fillText(printedName?.trim() || '', 48, startY + 40);
    return startY + 72;
  };

  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, width, height);
  ctx.strokeStyle = '#111111';
  ctx.lineWidth = 2;
  ctx.strokeRect(24, 24, width - 48, height - 48);

  ctx.fillStyle = '#111111';
  ctx.font = 'bold 26px sans-serif';
  ctx.fillText('No Ship Record', 320, 70);
  ctx.font = '14px sans-serif';
  ctx.fillText(`Order Number:  ${input.orderNumber}`, 48, 70);

  ctx.beginPath();
  ctx.moveTo(48, 90);
  ctx.lineTo(width - 48, 90);
  ctx.stroke();

  let y = 120;
  (['pharmacy', 'retail', 'sump', 'fuel'] as const).forEach((key, index) => {
    const x = 48 + index * 200;
    drawCheck(input.sections.includes(key), x, y);
    ctx.fillStyle = '#111111';
    ctx.font = '14px sans-serif';
    ctx.fillText(sectionLabels[key], x + 22, y);
  });

  y = 160;
  ctx.font = '14px sans-serif';
  ctx.fillText(`Store Number: ${input.storeNumber}`, 48, y);
  ctx.fillText(`Service Date : ${input.serviceDate}`, 520, y);
  y = wrapText(ctx, `Store Address: ${input.storeAddress}`, 48, y + 28, width - 96, 20);

  const pharmacy = input.sections.includes('pharmacy');
  const retail = input.sections.includes('retail');
  const sump = input.sections.includes('sump');
  const fuel = input.sections.includes('fuel');

  y += 24;
  ctx.font = 'bold 16px sans-serif';
  ctx.fillText('Pharmacy', 48, y);
  y += 24;
  ctx.font = '13px sans-serif';
  ctx.fillText(
    'Does store have a pharmacy? (if no, go to Retail / Front Store)',
    48,
    y,
  );
  y += 22;
  [
    'Clean Earth Serviced Store - No acute Rx waste to ship.',
    'Clean Earth Serviced Store - No non-acute Rx waste to ship.',
    'Clean Earth Serviced Store - No DEA controlled substance Rx waste to ship.',
    'Clean Earth Serviced Store - No State controlled substance Rx waste to ship.',
  ].forEach(line => {
    drawCheck(pharmacy, 48, y);
    ctx.fillStyle = '#111111';
    ctx.font = '13px sans-serif';
    ctx.fillText(line, 70, y);
    y += 22;
  });
  y = await drawSignaturePair(
    'Pharmacist In Charge Name (printed)',
    'Pharmacist In Charge Signature',
    printed.pharmacy,
    sigs.pharmacy,
    y + 8,
  );

  ctx.font = 'bold 16px sans-serif';
  ctx.fillText('Retail / Front Store', 48, y);
  y += 24;
  drawCheck(retail, 48, y);
  ctx.font = '13px sans-serif';
  ctx.fillText(
    'Clean Earth Serviced Store - No Front Store Area (retail) waste to ship.',
    70,
    y,
  );
  y = await drawSignaturePair(
    'Store Management Team Member and Title (printed)',
    'Store Management Team Member Signature',
    printed.retail,
    sigs.retail,
    y + 24,
  );

  ctx.font = 'bold 16px sans-serif';
  ctx.fillText('Sump Service', 48, y);
  y += 24;
  drawCheck(sump, 48, y);
  ctx.font = '13px sans-serif';
  ctx.fillText(
    'If Yes, Clean Earth Services Store - No sump waste to ship.',
    70,
    y,
  );
  y = await drawSignaturePair(
    'Store Management Team Member and Title (printed)',
    'Store Management Team Member Signature',
    printed.sump,
    sigs.sump,
    y + 24,
  );

  ctx.font = 'bold 16px sans-serif';
  ctx.fillText('Fuel Center', 48, y);
  y += 24;
  drawCheck(fuel, 48, y);
  ctx.font = '13px sans-serif';
  ctx.fillText(
    'Clean Earth Serviced Store - No Fuel Center waste to ship.',
    70,
    y,
  );
  y = await drawSignaturePair(
    'Store Management Team Member and Title (printed)',
    'Store Management Team Member Signature',
    printed.fuel,
    sigs.fuel,
    y + 24,
  );

  y = await drawSignaturePair(
    'Clean Earth Technican Name (printed)',
    'Clean Earth Technican Signature',
    printed.technician || input.technicianName,
    sigs.technician || input.signatureDataUri,
    y + 8,
  );

  ctx.beginPath();
  ctx.moveTo(48, y);
  ctx.lineTo(width - 48, y);
  ctx.stroke();
  ctx.fillStyle = '#555555';
  ctx.font = '12px sans-serif';
  ctx.fillText('Retail On-Site Waste Management Systems', 48, y + 24);

  return canvas.toDataURL('image/png');
}

async function replaceCategoryDocument(
  orderNumber: string,
  category: PhotoCategory,
  uri: string,
  caption?: string,
): Promise<void> {
  if (!isAutoGeneratedPhotoCategory(category)) {
    return;
  }
  const existingGroups = photoService.getDocumentGroupsForOrder(
    orderNumber,
    category,
  );
  for (const group of existingGroups) {
    await photoService.deleteDocumentGroup(orderNumber, group.id);
  }
  await photoService.addPhoto(orderNumber, uri, category, caption);
}

/**
 * Creates the LDR photo when a manifest is generated.
 * Skips if an LDR document already exists for the order.
 */
export async function ensureLdrDocumentPhoto(
  input: LdrDocumentPhotoInput,
): Promise<boolean> {
  if (!input.orderNumber || !input.trackingNumber.trim()) {
    return false;
  }
  if (photoService.hasDocumentForCategory(input.orderNumber, 'ldr')) {
    return true;
  }

  const uri = await renderLdrDataUri(input);
  await replaceCategoryDocument(
    input.orderNumber,
    'ldr',
    uri,
    'Auto-generated LDR',
  );
  return true;
}

/**
 * Creates the No Ship photo once a manifest exists and required
 * no-ship acknowledgement fields are complete.
 * Skips if a No Ship document already exists unless `force` is true.
 */
export async function ensureNoShipDocumentPhoto(
  input: NoShipDocumentPhotoInput,
  options?: {force?: boolean},
): Promise<boolean> {
  if (!input.orderNumber) {
    return false;
  }
  if (!input.signatureDataUri) {
    return false;
  }
  if (
    !options?.force &&
    photoService.hasDocumentForCategory(input.orderNumber, 'no-ship')
  ) {
    return true;
  }

  const uri = input.documentUri
    ? input.documentUri
    : await renderNoShipDataUri(input);
  await replaceCategoryDocument(
    input.orderNumber,
    'no-ship',
    uri,
    'Auto-generated No Ship record',
  );
  return true;
}

/** Clears auto-generated LDR / No Ship photos (e.g. after voiding a manifest). */
export async function clearAutoGeneratedDocumentPhotos(
  orderNumber: string,
): Promise<void> {
  for (const category of AUTO_CATEGORIES) {
    const groups = photoService.getDocumentGroupsForOrder(orderNumber, category);
    for (const group of groups) {
      await photoService.deleteDocumentGroup(orderNumber, group.id);
    }
  }
}

/** Useful for diagnostics / Platform-aware messaging. */
export const autoGeneratedDocumentsUseCanvas = Platform.OS === 'web';
