import React, {useState, useMemo, useEffect, useRef, useCallback} from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Alert,
  TextInput,
  Image,
  ImageStyle,
} from 'react-native';
import {Button} from '../../components/Button';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '../../components/Card';
import {Icon} from '../../components/Icon';
import {PersistentOrderHeader} from '../../components/PersistentOrderHeader';
import {SignatureCaptureModal} from '../../components/modals/SignatureCaptureModal';
import {
  OrderData,
  FlowStep,
  AddedContainer,
  MaterialsSupply,
  EquipmentPPE,
  ScannedDocument,
} from '../../types/wasteCollection';
import {SyncStatus} from '../../services/syncService';
import {syncService} from '../../services/syncService';
import {TimeTrackingRecord, stopTimeTracking} from '../../services/timeTrackingService';
import {serviceTypeTimeService, ServiceTypeTimeEntry} from '../../services/serviceTypeTimeService';
import {serviceTypeService} from '../../services/serviceTypeService';
import {
  photoService,
  OrderPhoto,
  isAutoGeneratedPhotoCategory,
  isSlottedShippingDocumentCategory,
  PhotoCategory,
} from '../../services/photoService';
import {colors} from '../../styles/theme';
import {styles} from './styles';

export interface OrderServiceScreenProps {
  // PersistentOrderHeader props
  selectedOrderData: OrderData | null;
  isOrderHeaderCollapsed: boolean;
  setIsOrderHeaderCollapsed: (collapsed: boolean) => void;
  setCurrentStep: (step: FlowStep) => void;
  elapsedTimeDisplay: string;
  currentOrderTimeTracking: TimeTrackingRecord | null;
  handleRequestPause: () => void;
  handleResumeTracking: () => void;
  setShowJobNotesModal: (show: boolean) => void;
  onOrderNotes: () => void;
  hasWorkOrderNotes: boolean;
  workOrderNotes: string;
  onRequestNotesBeforeComplete: (continueWithNotes: (notes: string) => void) => void;
  onClearWorkOrderNotes: (orderNumber: string) => void;
  validationState: {state: 'none' | 'warning' | 'error'; count: number};
  setShowValidationModal: (show: boolean) => void;
  setShowServiceCenterModal: (show: boolean) => void;
  selectedTruck: {number: string; description?: string} | null;
  truckId: string;
  selectedTrailer: {number: string; description?: string} | null;
  syncStatus: SyncStatus;
  pendingSyncCount: number;
  handleManualSync: () => void;
  serviceTypeBadgesForHeader: Array<{
    serviceTypeId: string;
    srNumber?: string;
    status: 'pending' | 'in-progress' | 'noship' | 'completed';
  }>;
  isOrderCompleted: (orderNumber: string) => boolean;

  // Order service-specific props
  activeContainers: AddedContainer[];
  selectedPrograms: Record<string, 'ship' | 'noship'>;
  materialsSupplies: MaterialsSupply[];
  equipmentPPE: EquipmentPPE[];
  addedContainers: AddedContainer[];
  scannedDocuments: ScannedDocument[];
  setCompletedOrders: (orders: string[] | ((prev: string[]) => string[])) => void;
  setOrderStatuses: (statuses: Record<string, OrderData['status']> | ((prev: Record<string, OrderData['status']>) => Record<string, OrderData['status']>)) => void;
  setSelectedOrderData: (order: OrderData | null) => void;
  setDashboardSelectedOrder: (order: OrderData | null) => void;
  setSelectedPrograms: (programs: Record<string, 'ship' | 'noship'> | ((prev: Record<string, 'ship' | 'noship'>) => Record<string, 'ship' | 'noship'>)) => void;
  setMaterialsSupplies: (materials: MaterialsSupply[] | ((prev: MaterialsSupply[]) => MaterialsSupply[])) => void;
  setEquipmentPPE: (equipment: EquipmentPPE[] | ((prev: EquipmentPPE[]) => EquipmentPPE[])) => void;
  setBarcode: (barcode: string) => void;
  setTareWeight: (weight: string) => void;
  setGrossWeight: (weight: string) => void;
  setShowChecklistModal: (show: boolean) => void;
  isChecklistCompleted: boolean;
  activeServiceTypeTimer: string | null;
  setActiveServiceTypeTimer: (timer: string | null) => void;
  serviceTypeTimeEntries: Map<string, ServiceTypeTimeEntry>;
  setServiceTypeTimeEntries: (entries: Map<string, ServiceTypeTimeEntry>) => void;
  activeTimeTracking: TimeTrackingRecord | null;
  setActiveTimeTracking: (tracking: TimeTrackingRecord | null) => void;
  setCurrentOrderTimeTracking: (tracking: TimeTrackingRecord | null) => void;
  setElapsedTimeDisplay: (display: string) => void;
  hasManifestForOrder: (orderNumber: string) => boolean;
  /** Manifest tracking number for the current order, when generated. */
  manifestTrackingNumber?: string | null;
  noshipByOrderAndServiceType: Record<string, Record<string, boolean>>;
  isServiceTypeNoShip: (orderNumber: string, serviceTypeId: string) => boolean;
  handleMarkServiceTypeComplete: () => void;
  showDocumentTypeSelector: boolean;
  setShowDocumentTypeSelector: (show: boolean) => void;
  /** Logged-in technician name shown on the Service Summary. */
  technicianName?: string;
  /** Navigate to a side-quest step and return here when done. */
  navigateToSideQuest: (
    step: FlowStep,
    options?: {photoCategory?: PhotoCategory},
  ) => void;
  onBack: () => void;
}

type IncompleteReasonAction =
  | {type: 'side-quest'; step: FlowStep; photoCategory?: PhotoCategory}
  | {type: 'step'; step: FlowStep}
  | {type: 'notes'}
  | {type: 'focus-ack'};

type IncompleteReason = {
  id: string;
  reason: string;
  severity: 'warning' | 'error';
  waivable?: boolean;
  action?: IncompleteReasonAction;
  hint?: string;
};

export const OrderServiceScreen: React.FC<OrderServiceScreenProps> = ({
  selectedOrderData,
  isOrderHeaderCollapsed,
  setIsOrderHeaderCollapsed,
  setCurrentStep,
  elapsedTimeDisplay,
  currentOrderTimeTracking,
  handleRequestPause,
  handleResumeTracking,
  setShowJobNotesModal,
  onOrderNotes,
  hasWorkOrderNotes,
  workOrderNotes,
  onRequestNotesBeforeComplete,
  onClearWorkOrderNotes,
  validationState,
  setShowValidationModal,
  setShowServiceCenterModal,
  selectedTruck,
  truckId,
  selectedTrailer,
  syncStatus,
  pendingSyncCount,
  handleManualSync,
  serviceTypeBadgesForHeader,
  isOrderCompleted,
  activeContainers,
  selectedPrograms,
  materialsSupplies,
  equipmentPPE,
  addedContainers,
  scannedDocuments,
  setCompletedOrders,
  setOrderStatuses,
  setSelectedOrderData,
  setDashboardSelectedOrder,
  setSelectedPrograms,
  setMaterialsSupplies,
  setEquipmentPPE,
  setBarcode,
  setTareWeight,
  setGrossWeight,
  setShowChecklistModal,
  isChecklistCompleted,
  activeServiceTypeTimer,
  setActiveServiceTypeTimer,
  serviceTypeTimeEntries,
  setServiceTypeTimeEntries,
  activeTimeTracking,
  setActiveTimeTracking,
  setCurrentOrderTimeTracking,
  setElapsedTimeDisplay,
  hasManifestForOrder,
  manifestTrackingNumber = null,
  noshipByOrderAndServiceType,
  isServiceTypeNoShip,
  handleMarkServiceTypeComplete,
  showDocumentTypeSelector,
  setShowDocumentTypeSelector,
  technicianName,
  navigateToSideQuest,
  onBack,
}) => {
  const totalNetWeight = activeContainers.reduce(
    (sum, c) => sum + c.netWeight,
    0,
  );
  const programsToShip = Object.values(selectedPrograms).filter(
    p => p === 'ship',
  ).length;

  // Get service type time entries for this order
  const serviceTypeTimeEntriesForOrder = selectedOrderData
    ? serviceTypeTimeService.getTimeEntriesForOrder(selectedOrderData.orderNumber)
    : [];
  const totalServiceTimeMinutes = selectedOrderData
    ? serviceTypeTimeService.getTotalDurationForOrder(selectedOrderData.orderNumber)
    : 0;

  // Check if all service types are complete (timed end or No-Ship)
  const allServiceTypesComplete = selectedOrderData
    ? selectedOrderData.programs.every(serviceTypeId => {
        if (
          isServiceTypeNoShip(selectedOrderData.orderNumber, serviceTypeId)
        ) {
          return true;
        }
        const entry = serviceTypeTimeService.getTimeEntry(
          selectedOrderData.orderNumber,
          serviceTypeId,
        );
        return entry?.startTime != null && entry?.endTime != null;
      })
    : false;

  // Local state
  const [customerFirstName, setCustomerFirstName] = useState('');
  const [customerLastName, setCustomerLastName] = useState('');
  const [customerEmail, setCustomerEmail] = useState('');
  const [customerSignature, setCustomerSignature] = useState<string | null>(
    null,
  );
  const [showSignatureModal, setShowSignatureModal] = useState(false);
  const [acknowledgeIncomplete, setAcknowledgeIncomplete] = useState(false);
  const [orderPhotos, setOrderPhotos] = useState<OrderPhoto[]>([]);
  const summaryScrollRef = useRef<ScrollView>(null);
  const scrollContainerRef = useRef<View>(null);
  const customerAckRef = useRef<View>(null);
  const scrollOffsetY = useRef(0);

  // Reset acknowledgment fields when switching orders.
  useEffect(() => {
    setCustomerFirstName('');
    setCustomerLastName('');
    setCustomerEmail('');
    setCustomerSignature(null);
    setShowSignatureModal(false);
    setAcknowledgeIncomplete(false);
  }, [selectedOrderData?.orderNumber]);

  useEffect(() => {
    if (!selectedOrderData?.orderNumber) {
      setOrderPhotos([]);
      return;
    }
    return photoService.onPhotosChange(
      selectedOrderData.orderNumber,
      setOrderPhotos,
    );
  }, [selectedOrderData?.orderNumber]);

  // Compute incomplete reasons for this order
  const incompleteReasons = useMemo((): IncompleteReason[] => {
    const reasons: IncompleteReason[] = [];

    if (selectedOrderData?.orderNumber) {
      photoService
        .getMissingCloseoutPhotoCategories(selectedOrderData.orderNumber)
        .forEach(category => {
          // Auto-generated docs (LDR / No Ship) never appear as hard warnings.
          if (isAutoGeneratedPhotoCategory(category)) {
            return;
          }
          const label = photoService.getCategoryLabel(category);
          const isShippingDoc =
            photoService.getShippingDocumentCategories().includes(category);
          const isMilestone =
            category === 'before-service' || category === 'after-service';
          const isSlotted = isSlottedShippingDocumentCategory(category);
          const missingSlots = isSlotted
            ? photoService.getMissingDocumentSlots(
                selectedOrderData.orderNumber,
                category,
              )
            : [];
          const missingSlotLabels = missingSlots.map(s => s.label).join(', ');
          reasons.push({
            id: `missing-photo-${category}`,
            reason: isSlotted
              ? missingSlots.length > 0
                ? `${label}: at least 1 image required for each document (${missingSlotLabels} missing)`
                : `${label}: at least 1 image required for each document`
              : isShippingDoc
                ? `At least 1 ${label} image required`
                : isMilestone
                  ? `${label} photo required (capture at least one)`
                  : `${label} photo required`,
            severity: 'error',
            waivable: false,
            action: {
              type: 'side-quest',
              step: 'order-photos',
              photoCategory: category,
            },
            hint: isSlotted
              ? `Tap to open Photos and add an image to each ${label} slot`
              : 'Tap to open Photos and capture required photos',
          });
        });
    }

    // Check if no containers were added
    if (addedContainers.length === 0) {
      reasons.push({
        id: 'no-containers',
        reason: 'No containers have been added to this order',
        severity: 'warning',
        action: {type: 'step', step: 'container-summary'},
        hint: 'Tap to go to Container Summary to add containers',
      });
    }

    // Soft warning: work order notes are optional but encouraged
    if (!workOrderNotes.trim()) {
      reasons.push({
        id: 'no-work-order-notes',
        reason: 'No work order notes have been entered',
        severity: 'warning',
        action: {type: 'notes'},
        hint: 'Tap to open Order Notes (optional)',
      });
    }

    // Hard stop: customer name + digital signature required for No-ship and SSR closeout
    if (!customerFirstName.trim() || !customerLastName.trim()) {
      reasons.push({
        id: 'missing-customer-name',
        reason: 'Customer first and last name are required',
        severity: 'error',
        waivable: false,
        action: {type: 'focus-ack'},
        hint: 'Tap to go to customer acknowledgment',
      });
    }
    if (!customerSignature) {
      reasons.push({
        id: 'missing-customer-signature',
        reason: 'Digital customer signature is required for Service Summary / No-ship closeout',
        severity: 'error',
        waivable: false,
        action: {type: 'focus-ack'},
        hint: 'Tap to capture customer signature',
      });
    }

    return reasons;
  }, [
    selectedOrderData,
    addedContainers,
    orderPhotos,
    workOrderNotes,
    customerFirstName,
    customerLastName,
    customerSignature,
  ]);

  const scrollToCustomerAck = useCallback(() => {
    customerAckRef.current?.measureInWindow((_ackX, ackY) => {
      scrollContainerRef.current?.measureInWindow((_sx, scrollY) => {
        const targetY = Math.max(
          0,
          scrollOffsetY.current + (ackY - scrollY) - 16,
        );
        summaryScrollRef.current?.scrollTo({y: targetY, animated: true});
      });
    });
  }, []);

  const handleIncompleteReasonPress = useCallback(
    (item: IncompleteReason) => {
      if (!item.action) {
        return;
      }
      switch (item.action.type) {
        case 'side-quest':
          navigateToSideQuest(
            item.action.step,
            item.action.photoCategory
              ? {photoCategory: item.action.photoCategory}
              : undefined,
          );
          break;
        case 'step':
          setCurrentStep(item.action.step);
          break;
        case 'notes':
          onOrderNotes();
          break;
        case 'focus-ack':
          scrollToCustomerAck();
          break;
      }
    },
    [navigateToSideQuest, setCurrentStep, onOrderNotes, scrollToCustomerAck],
  );

  const hasHardBlockingErrors = incompleteReasons.some(
    r => r.severity === 'error' && r.waivable === false,
  );
  const hasWaivableBlockingErrors = incompleteReasons.some(
    r => r.severity === 'error' && r.waivable !== false,
  );
  const hasSoftWarnings = incompleteReasons.some(
    r => r.severity === 'warning',
  );
  /** Soft warnings (and any waivable errors) require explicit consent to complete. */
  const requiresIncompleteAcknowledgment =
    hasSoftWarnings || hasWaivableBlockingErrors;

  const handleCompleteOrder = async () => {
    if (!customerFirstName.trim() || !customerLastName.trim()) {
      Alert.alert(
        'Required Fields',
        'Please enter customer first name and last name on the Service Summary.',
      );
      return;
    }

    if (!customerSignature) {
      Alert.alert(
        'Signature Required',
        'Please capture the customer signature on the Service Summary.',
      );
      return;
    }

    // Check for blocking errors that haven't been acknowledged
    if (hasHardBlockingErrors) {
      const orderNumber = selectedOrderData?.orderNumber;
      const missing = orderNumber
        ? photoService.getMissingCloseoutPhotoCategories(orderNumber)
        : [];
      const lines = missing.map(category => {
        const label = photoService.getCategoryLabel(category);
        if (isSlottedShippingDocumentCategory(category) && orderNumber) {
          const slots = photoService.getMissingDocumentSlots(
            orderNumber,
            category,
          );
          if (slots.length > 0) {
            return `• ${label}: ${slots.map(s => s.label).join(', ')}`;
          }
        }
        return `• ${label}`;
      });
      Alert.alert(
        'Required photos missing',
        lines.length > 0
          ? `Capture at least one image for each required document before completing:\n\n${lines.join('\n')}`
          : 'Required photos must be captured before completing this order.',
      );
      return;
    }

    if (requiresIncompleteAcknowledgment && !acknowledgeIncomplete) {
      Alert.alert(
        'Acknowledgment Required',
        'This order has soft warnings that must be acknowledged before completing. Please review the warnings above and check the acknowledgment box to continue.',
      );
      return;
    }

    if (!selectedOrderData) return;

    const performCompletion = async (notesForSync: string) => {
      // Store the service type that's being completed (before ending it)
      const completingServiceTypeId = activeServiceTypeTimer;

      // If there's an active service type timer, end it first
      if (activeServiceTypeTimer) {
        try {
          await serviceTypeTimeService.endServiceType(
            selectedOrderData.orderNumber,
            activeServiceTypeTimer,
          );

          // Reload service type time entries
          const entries = new Map<string, ServiceTypeTimeEntry>();
          selectedOrderData.programs.forEach(stId => {
            const entry = serviceTypeTimeService.getTimeEntry(
              selectedOrderData.orderNumber,
              stId,
            );
            if (entry) {
              entries.set(stId, entry);
            }
          });
          setServiceTypeTimeEntries(entries);
          setActiveServiceTypeTimer(null);
        } catch (error) {
          console.error('Error ending service type time tracking:', error);
          Alert.alert('Error', 'Failed to end service type time tracking');
          return;
        }
      }

      // Check if all service types are complete (timed end or No-Ship)
      const allServiceTypesCompleteNow = selectedOrderData.programs.every(
        serviceTypeId => {
          if (
            isServiceTypeNoShip(selectedOrderData.orderNumber, serviceTypeId)
          ) {
            return true;
          }
          const entry = serviceTypeTimeService.getTimeEntry(
            selectedOrderData.orderNumber,
            serviceTypeId,
          );
          return entry?.startTime != null && entry?.endTime != null;
        },
      );

      if (allServiceTypesCompleteNow) {
        // All service types are complete - complete the entire order
        const trimmedNotes = notesForSync.trim();
        // Queue order completion for sync
        await syncService.addPendingOperation('order', {
          orderNumber: selectedOrderData.orderNumber,
          completed: true,
          containers: addedContainers,
          programs: selectedPrograms,
          materialsSupplies,
          equipmentPPE,
          totalNetWeight,
          programsToShip,
          customerAcknowledgment: {
            firstName: customerFirstName,
            lastName: customerLastName,
            email: customerEmail || undefined,
            signatureImageUri: customerSignature || undefined,
            acknowledgedAt: new Date().toISOString(),
          },
          ...(trimmedNotes
            ? {
                workOrderNotes: trimmedNotes,
                needsReview: true,
              }
            : {}),
        });

        // Stop overall order time tracking
        try {
          await stopTimeTracking(selectedOrderData.orderNumber);
          // Clear active tracking if this was the active order
          if (activeTimeTracking?.orderNumber === selectedOrderData.orderNumber) {
            setActiveTimeTracking(null);
          }
          // Clear current order tracking
          if (currentOrderTimeTracking?.orderNumber === selectedOrderData.orderNumber) {
            setCurrentOrderTimeTracking(null);
            setElapsedTimeDisplay('');
          }
        } catch (error) {
          console.error('Error stopping time tracking:', error);
        }

        // Mark order as completed
        setCompletedOrders(prev => [...prev, selectedOrderData.orderNumber]);
        onClearWorkOrderNotes(selectedOrderData.orderNumber);
        // Update order status
        setOrderStatuses(prev => ({
          ...prev,
          [selectedOrderData.orderNumber]: 'Completed',
        }));
        // Reset state and clear selected order so user cannot open manifest/service types for completed order
        setSelectedOrderData(null);
        setDashboardSelectedOrder(null);
        // Keep addedContainers — they persist on truck until user marks and confirms drop in Record Drop flow
        setSelectedPrograms({});
        setMaterialsSupplies([]);
        setEquipmentPPE([]);
        setBarcode('');
        setTareWeight('45');
        setGrossWeight('285');
        setCurrentStep('dashboard');
      } else {
        // Not all service types are complete - just complete the current service type
        // Reload service type time entries to reflect the updated state
        const entries = new Map<string, ServiceTypeTimeEntry>();
        selectedOrderData.programs.forEach(stId => {
          const entry = serviceTypeTimeService.getTimeEntry(
            selectedOrderData.orderNumber,
            stId,
          );
          if (entry) {
            entries.set(stId, entry);
          }
        });
        setServiceTypeTimeEntries(entries);

        // Update order status to "Partial" (not all service types complete yet)
        setOrderStatuses(prev => ({
          ...prev,
          [selectedOrderData.orderNumber]: 'Partial',
        }));

        // Navigate to dashboard after completing service type
        setCurrentStep('dashboard');
        // Keep the order selected so user can start the next service type
        // Don't clear selectedOrderData - let user see the order and start next service type
      }
    };

    // Final work-order completion always opens the Work Order Notes modal
    // (Skip / Save & Continue) so the technician confirms before closing out.
    if (!allServiceTypesComplete) {
      await performCompletion(workOrderNotes.trim());
    } else {
      onRequestNotesBeforeComplete(notes => {
        void performCompletion(notes);
      });
    }
  };

  // Customer Acknowledgment View
  if (!selectedOrderData) return null;

  return (
    <View style={styles.container}>
      <PersistentOrderHeader
        orderData={selectedOrderData}
        isCollapsed={isOrderHeaderCollapsed}
        onToggleCollapse={() => setIsOrderHeaderCollapsed(!isOrderHeaderCollapsed)}
        onBackPress={onBack}
        subtitle="Customer Acknowledgment"
        elapsedTimeDisplay={elapsedTimeDisplay && currentOrderTimeTracking && selectedOrderData ? elapsedTimeDisplay : undefined}
        isPaused={Boolean(currentOrderTimeTracking?.pausedAt)}
        onPause={handleRequestPause}
        onResume={handleResumeTracking}
        onViewNotes={() => {
          setShowJobNotesModal(true);
        }}
        onOrderNotes={onOrderNotes}
        hasWorkOrderNotes={hasWorkOrderNotes}
        validationState={validationState}
        onViewValidation={() => setShowValidationModal(true)}
        onViewServiceCenter={() => setShowServiceCenterModal(true)}
        truckNumber={selectedTruck?.number || truckId || undefined}
        trailerNumber={selectedTrailer?.number || null}
        syncStatus={syncStatus}
        pendingSyncCount={pendingSyncCount}
        onSync={handleManualSync}
        serviceTypeBadges={serviceTypeBadgesForHeader}
      />

      <View ref={scrollContainerRef} collapsable={false} style={styles.scrollViewContainer}>
        <ScrollView
          ref={summaryScrollRef}
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          keyboardShouldPersistTaps="handled"
          keyboardDismissMode="on-drag"
          removeClippedSubviews={false}
          scrollEventThrottle={16}
          onScroll={event => {
            scrollOffsetY.current = event.nativeEvent.contentOffset.y;
          }}>
          {/* Page toolbar */}
          <View style={styles.serviceSummaryPageToolbar}>
            <TouchableOpacity
              style={styles.serviceSummaryPrintBtn}
              onPress={() => {
                Alert.alert(
                  'Printing Service Summary',
                  `Order: ${selectedOrderData?.orderNumber}\n\nService Summary printer integration will be implemented here.`,
                  [{text: 'OK'}],
                );
              }}
              accessibilityRole="button"
              accessibilityLabel="Print Service Summary"
              hitSlop={{top: 8, bottom: 8, left: 8, right: 8}}>
              <Icon name="print" size={22} color={colors.foreground} />
            </TouchableOpacity>
          </View>

          {/* Service Summary - Matching Print Layout */}
          <View style={styles.serviceSummaryContainer}>
            {/* Header */}
            <View style={styles.serviceSummaryHeader}>
              <Text style={styles.serviceSummaryTitle}>Service Summary</Text>
              <View style={styles.serviceSummaryLogo}>
                <Text style={styles.serviceSummaryLogoText}>CleanEarth</Text>
                <View style={styles.serviceSummaryLogoDot} />
              </View>
            </View>

            {/* Work Order # and Date Row */}
            <View style={styles.serviceSummaryTopRow}>
              <View style={styles.serviceSummaryTopItem}>
                <Text style={styles.serviceSummaryFieldLabel}>Work Order #:</Text>
                <Text style={styles.serviceSummaryFieldValue}>{selectedOrderData?.orderNumber || 'N/A'}</Text>
              </View>
              <View style={styles.serviceSummaryTopItem}>
                <Text style={styles.serviceSummaryFieldLabel}>Date:</Text>
                <Text style={styles.serviceSummaryFieldValue}>{new Date().toLocaleDateString()}</Text>
              </View>
            </View>

            {isChecklistCompleted && (
              <View style={styles.checklistCompletedBadge}>
                <Icon name="check-circle" size={16} color={colors.success} />
                <Text style={styles.checklistCompletedBadgeText}>
                  Service Checklist Completed
                </Text>
              </View>
            )}

            {/* Customer and Generator Section */}
            <View style={styles.serviceSummaryTwoColumn}>
              {/* CUSTOMER Section */}
              <View style={styles.serviceSummaryColumnBox}>
                <View style={styles.serviceSummarySectionHeader}>
                  <Text style={styles.serviceSummarySectionHeaderText}>CUSTOMER:</Text>
                </View>
                <View style={styles.serviceSummarySectionBody}>
                  <Text style={styles.serviceSummaryText}>HDDS</Text>
                  <Text style={styles.serviceSummaryText}>HDDS</Text>
                  <Text style={styles.serviceSummaryText}>5250 Triangle Parkway Suite 200</Text>
                  <Text style={styles.serviceSummaryText}>Peachtree Corners, GA 30092</Text>
                  <View style={styles.serviceSummaryFieldRow}>
                    <Text style={styles.serviceSummaryFieldLabel}>Phone:</Text>
                    <Text style={styles.serviceSummaryText}></Text>
                  </View>
                  <View style={styles.serviceSummaryFieldRow}>
                    <Text style={styles.serviceSummaryFieldLabel}>Billing:</Text>
                    <Text style={styles.serviceSummaryText}>A40000167</Text>
                  </View>
                </View>
              </View>

              {/* GENERATOR Section */}
              <View style={styles.serviceSummaryColumnBox}>
                <View style={styles.serviceSummarySectionHeader}>
                  <Text style={styles.serviceSummarySectionHeaderText}>GENERATOR:</Text>
                </View>
                <View style={styles.serviceSummarySectionBody}>
                  <Text style={styles.serviceSummaryText}>HDDS</Text>
                  <Text style={styles.serviceSummaryText}>Soleo Health#</Text>
                  <Text style={styles.serviceSummaryText}>1324 W Winton Ave</Text>
                  <Text style={styles.serviceSummaryText}>Hayward, CA 94545-1408</Text>
                  <View style={styles.serviceSummaryFieldRow}>
                    <Text style={styles.serviceSummaryFieldLabel}>Generator:</Text>
                    <Text style={styles.serviceSummaryText}>(510) 362-7360</Text>
                  </View>
                  <View style={styles.serviceSummaryFieldRow}>
                    <Text style={styles.serviceSummaryFieldLabel}>EPA ID:</Text>
                    <Text style={styles.serviceSummaryText}>CAL000483809</Text>
                  </View>
                </View>
              </View>
            </View>

            {/* WORK ORDER DETAILS Section */}
            <View style={styles.serviceSummarySection}>
              <View style={styles.serviceSummarySectionHeader}>
                <Text style={styles.serviceSummarySectionHeaderText}>WORK ORDER DETAILS</Text>
              </View>
              <View style={styles.serviceSummaryTableRow}>
                <View style={[styles.serviceSummaryTableCell, {flex: 1}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Account Rep</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {flex: 1}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Terms</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {flex: 1}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Purchase Order</Text>
                </View>
              </View>
              <View style={styles.serviceSummaryTableRow}>
                <View style={[styles.serviceSummaryTableCell, {flex: 1}]}>
                  <Text style={styles.serviceSummaryTableValue}>House Account</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {flex: 1}]}>
                  <Text style={styles.serviceSummaryTableValue}>ON RECEIPT(4)</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {flex: 1}]}>
                  <Text style={styles.serviceSummaryTableValue}>West</Text>
                </View>
              </View>
            </View>

            {/* SERVICE TYPE TIME BREAKDOWN Section */}
            {serviceTypeTimeEntriesForOrder.length > 0 && (
              <View style={styles.serviceSummarySection}>
                <View style={styles.serviceSummarySectionHeader}>
                  <Text style={styles.serviceSummarySectionHeaderText}>SERVICE TYPE TIME BREAKDOWN</Text>
                </View>
                {serviceTypeTimeEntriesForOrder.map((entry, index) => {
                  const serviceType = serviceTypeService.getServiceType(entry.serviceTypeId);
                  return (
                    <View key={entry.serviceTypeId} style={styles.serviceSummaryTimeRow}>
                      <View style={styles.serviceSummaryTimeServiceType}>
                        <Text style={styles.serviceSummaryTimeServiceTypeName}>
                          {serviceType?.name || entry.serviceTypeId}:
                        </Text>
                      </View>
                      <View style={styles.serviceSummaryTimeDetails}>
                        <Text style={styles.serviceSummaryTimeText}>
                          {entry.startTime
                            ? serviceTypeTimeService.formatTime(entry.startTime)
                            : 'N/A'}{' '}
                          –{' '}
                          {entry.endTime
                            ? serviceTypeTimeService.formatTime(entry.endTime)
                            : 'In Progress'}{' '}
                          ({entry.durationMinutes !== null && entry.durationMinutes !== undefined
                            ? serviceTypeTimeService.formatDuration(entry.durationMinutes)
                            : 'N/A'})
                        </Text>
                      </View>
                    </View>
                  );
                })}
                {totalServiceTimeMinutes > 0 && (
                  <View style={styles.serviceSummaryTimeTotal}>
                    <Text style={styles.serviceSummaryTimeTotalLabel}>Total Service Time:</Text>
                    <Text style={styles.serviceSummaryTimeTotalValue}>
                      {serviceTypeTimeService.formatDuration(totalServiceTimeMinutes)}
                    </Text>
                  </View>
                )}
                {currentOrderTimeTracking && (
                  <View style={styles.serviceSummaryTimeTotal}>
                    <Text style={styles.serviceSummaryTimeTotalLabel}>Order Time (Total On-Site):</Text>
                    <Text style={styles.serviceSummaryTimeTotalValue}>
                      {elapsedTimeDisplay || 'N/A'}
                    </Text>
                  </View>
                )}
              </View>
            )}

            {/* WORK PERFORMED Section */}
            <View style={styles.serviceSummarySection}>
              <View style={styles.serviceSummarySectionHeader}>
                <Text style={styles.serviceSummarySectionHeaderText}>WORK PERFORMED</Text>
              </View>
              <View style={styles.serviceSummaryTableRow}>
                <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Profile #</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {flex: 2}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Profile Name</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Size</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {width: 60}]}>
                  <Text style={styles.serviceSummaryTableHeader}>VOL</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {width: 40}]}>
                  <Text style={styles.serviceSummaryTableHeader}>UOM</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Number of Containers</Text>
                </View>
              </View>
              {addedContainers.length > 0 ? (
                addedContainers.map((container, index) => (
                  <View key={container.id} style={styles.serviceSummaryTableRow}>
                    <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                      <Text style={styles.serviceSummaryTableValue}>5014883{index + 3}</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {flex: 2}]}>
                      <Text style={styles.serviceSummaryTableValue}>{container.streamName}</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                      <Text style={styles.serviceSummaryTableValue}>{container.containerSize}</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 60}]}>
                      <Text style={styles.serviceSummaryTableValue}>{String(container.netWeight).padStart(5, '0')}</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 40}]}>
                      <Text style={styles.serviceSummaryTableValue}>P</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                      <Text style={styles.serviceSummaryTableValue}>1</Text>
                    </View>
                  </View>
                ))
              ) : (
                <>
                  <View style={styles.serviceSummaryTableRow}>
                    <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                      <Text style={styles.serviceSummaryTableValue}>50148833</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {flex: 2}]}>
                      <Text style={styles.serviceSummaryTableValue}>W PHARMACEUTICAL AEROSOLS/ INHALERS</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                      <Text style={styles.serviceSummaryTableValue}>Box 2.5 Ga</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 60}]}>
                      <Text style={styles.serviceSummaryTableValue}>00001</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 40}]}>
                      <Text style={styles.serviceSummaryTableValue}>P</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                      <Text style={styles.serviceSummaryTableValue}>1</Text>
                    </View>
                  </View>
                  <View style={styles.serviceSummaryTableRow}>
                    <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                      <Text style={styles.serviceSummaryTableValue}>50148851</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {flex: 2}]}>
                      <Text style={styles.serviceSummaryTableValue}>FLAMMABLE/CORROSIVE PHARMACEUTICALS (AMMONIA INHAL</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                      <Text style={styles.serviceSummaryTableValue}>Box 2.5 Ga</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 60}]}>
                      <Text style={styles.serviceSummaryTableValue}>00002</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 40}]}>
                      <Text style={styles.serviceSummaryTableValue}>P</Text>
                    </View>
                    <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                      <Text style={styles.serviceSummaryTableValue}>1</Text>
                    </View>
                  </View>
                </>
              )}
            </View>

            {/* LABOR, MATERIAL AND SUPPLIES USED Section */}
            <View style={styles.serviceSummarySection}>
              <View style={styles.serviceSummarySectionHeader}>
                <Text style={styles.serviceSummarySectionHeaderText}>LABOR, MATERIAL AND SUPPLIES USED</Text>
              </View>
              <View style={styles.serviceSummaryTableRow}>
                <View style={[styles.serviceSummaryTableCell, {width: 100}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Product</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {flex: 2}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Description</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                  <Text style={styles.serviceSummaryTableHeader}># Delivered</Text>
                </View>
              </View>
              {materialsSupplies.filter(m => m.type === 'used').length > 0 ? (
                materialsSupplies
                  .filter(m => m.type === 'used')
                  .map(material => (
                    <View key={material.id} style={styles.serviceSummaryTableRow}>
                      <View style={[styles.serviceSummaryTableCell, {width: 100}]}>
                        <Text style={styles.serviceSummaryTableValue}>{material.itemNumber}</Text>
                      </View>
                      <View style={[styles.serviceSummaryTableCell, {flex: 2}]}>
                        <Text style={styles.serviceSummaryTableValue}>{material.description}</Text>
                      </View>
                      <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                        <Text style={styles.serviceSummaryTableValue}>{material.quantity}</Text>
                      </View>
                    </View>
                  ))
              ) : (
                <View style={[styles.serviceSummaryTableRow, {minHeight: 30}]}>
                  <View style={[styles.serviceSummaryTableCell, {width: 100}]} />
                  <View style={[styles.serviceSummaryTableCell, {flex: 2}]} />
                  <View style={[styles.serviceSummaryTableCell, {width: 80}]} />
                </View>
              )}
            </View>

            {/* LABOR, MATERIAL AND SUPPLIES LEFT BEHIND Section */}
            <View style={styles.serviceSummarySection}>
              <View style={styles.serviceSummarySectionHeader}>
                <Text style={styles.serviceSummarySectionHeaderText}>LABOR, MATERIAL AND SUPPLIES LEFT BEHIND</Text>
              </View>
              <View style={styles.serviceSummaryTableRow}>
                <View style={[styles.serviceSummaryTableCell, {width: 100}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Product</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {flex: 2}]}>
                  <Text style={styles.serviceSummaryTableHeader}>Description</Text>
                </View>
                <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                  <Text style={styles.serviceSummaryTableHeader}># Delivered</Text>
                </View>
              </View>
              {materialsSupplies.filter(m => m.type === 'left_behind').length > 0 ? (
                materialsSupplies
                  .filter(m => m.type === 'left_behind')
                  .map(material => (
                    <View key={material.id} style={styles.serviceSummaryTableRow}>
                      <View style={[styles.serviceSummaryTableCell, {width: 100}]}>
                        <Text style={styles.serviceSummaryTableValue}>{material.itemNumber}</Text>
                      </View>
                      <View style={[styles.serviceSummaryTableCell, {flex: 2}]}>
                        <Text style={styles.serviceSummaryTableValue}>{material.description}</Text>
                      </View>
                      <View style={[styles.serviceSummaryTableCell, {width: 80}]}>
                        <Text style={styles.serviceSummaryTableValue}>{material.quantity}</Text>
                      </View>
                    </View>
                  ))
              ) : (
                <View style={[styles.serviceSummaryTableRow, {minHeight: 30}]}>
                  <View style={[styles.serviceSummaryTableCell, {width: 100}]} />
                  <View style={[styles.serviceSummaryTableCell, {flex: 2}]} />
                  <View style={[styles.serviceSummaryTableCell, {width: 80}]} />
                </View>
              )}
            </View>

            {/* Customer Acknowledgement Section */}
            <View
              ref={customerAckRef}
              collapsable={false}
              style={styles.serviceSummaryAcknowledgement}>
              <View style={styles.serviceSummaryAckLeft}>
                <Text style={styles.serviceSummaryAckTitle}>Customer{'\n'}Acknowledgement:</Text>
              </View>
              <View style={styles.serviceSummaryAckMiddle}>
                <View style={styles.serviceSummaryAckField}>
                  <Text style={styles.serviceSummaryAckLabel}>Last Name:</Text>
                  <View style={styles.serviceSummaryAckInputLine}>
                    <TextInput
                      style={styles.serviceSummaryAckInput}
                      value={customerLastName}
                      onChangeText={setCustomerLastName}
                      placeholder="Tap to type name"
                      placeholderTextColor="#9ca3af"
                      autoCorrect={false}
                      autoCapitalize="words"
                      returnKeyType="next"
                      accessibilityLabel="Customer last name"
                    />
                  </View>
                </View>
                <View style={styles.serviceSummaryAckField}>
                  <Text style={styles.serviceSummaryAckLabel}>First Name:</Text>
                  <View style={styles.serviceSummaryAckInputLine}>
                    <TextInput
                      style={styles.serviceSummaryAckInput}
                      value={customerFirstName}
                      onChangeText={setCustomerFirstName}
                      placeholder="Tap to type name"
                      placeholderTextColor="#9ca3af"
                      autoCorrect={false}
                      autoCapitalize="words"
                      returnKeyType="next"
                      accessibilityLabel="Customer first name"
                    />
                  </View>
                </View>
                <View style={styles.serviceSummaryAckField}>
                  <Text style={styles.serviceSummaryAckLabel}>Email:</Text>
                  <View style={styles.serviceSummaryAckInputLine}>
                    <TextInput
                      style={styles.serviceSummaryAckInput}
                      value={customerEmail}
                      onChangeText={setCustomerEmail}
                      placeholder="Tap to type email"
                      placeholderTextColor="#9ca3af"
                      keyboardType="email-address"
                      autoCapitalize="none"
                      autoCorrect={false}
                      returnKeyType="done"
                      accessibilityLabel="Customer email"
                    />
                  </View>
                </View>
                <View style={styles.serviceSummaryAckField}>
                  <Text style={styles.serviceSummaryAckLabel}>Signature:</Text>
                  <TouchableOpacity
                    style={styles.serviceSummaryAckSignatureLine}
                    onPress={() => setShowSignatureModal(true)}
                    activeOpacity={0.7}
                    accessibilityRole="button"
                    accessibilityLabel={
                      customerSignature
                        ? 'Customer signature, tap to resign'
                        : 'Customer signature, tap to sign'
                    }>
                    {customerSignature ? (
                      <Image
                        source={{uri: customerSignature}}
                        style={
                          styles.serviceSummaryAckSignatureImage as ImageStyle
                        }
                        resizeMode="contain"
                      />
                    ) : (
                      <Text style={styles.serviceSummaryAckSignaturePlaceholder}>
                        Tap to sign
                      </Text>
                    )}
                  </TouchableOpacity>
                </View>
              </View>
              <View style={styles.serviceSummaryAckRight}>
                <View style={styles.serviceSummaryAckField}>
                  <Text style={styles.serviceSummaryAckLabel}>Technician:</Text>
                  <Text style={styles.serviceSummaryAckValue}>
                    {(technicianName || '').trim() || '—'}
                  </Text>
                </View>
              </View>
            </View>

            {/* Footer */}
            <View style={styles.serviceSummaryFooter}>
              <View style={styles.serviceSummaryFooterItem}>
                <Text style={styles.serviceSummaryFooterLabel}>Work Order #:</Text>
                <Text style={styles.serviceSummaryFooterValue}>{selectedOrderData?.orderNumber || 'N/A'}</Text>
              </View>
              <View style={styles.serviceSummaryFooterItem}>
                <Text style={styles.serviceSummaryFooterLabel}>On Site Time:</Text>
                <Text style={styles.serviceSummaryFooterValueMuted}>Not Available - Offline</Text>
              </View>
              <View style={styles.serviceSummaryFooterItem}>
                <Text style={styles.serviceSummaryFooterLabel}>Departure Time:</Text>
                <Text style={styles.serviceSummaryFooterValue}>11/14/2025 9:36:24 AM</Text>
              </View>
            </View>
          </View>

          {/* Incomplete Reasons Warning */}
          {incompleteReasons.length > 0 && (
            <Card style={styles.incompleteWarningCard}>
              <CardHeader>
                <CardTitle>
                  <View style={styles.incompleteWarningHeader}>
                    <Icon name="warning" size={20} color="#B45309" />
                    <Text style={styles.incompleteWarningTitleText}>
                      Incomplete Order - Action Required
                    </Text>
                  </View>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <Text style={styles.incompleteWarningDescription}>
                  {hasHardBlockingErrors
                    ? 'Hard-stop items must be resolved before completing. Soft warnings can be acknowledged to continue.'
                    : 'Soft warnings are listed below. Check the acknowledgment box to confirm you have reviewed them and still wish to complete this order.'}
                </Text>

                <View style={styles.incompleteReasonsList}>
                  {incompleteReasons.map(item => {
                    const isActionable = Boolean(item.action);
                    const rowStyle = [
                      styles.incompleteReasonItem,
                      item.severity === 'error'
                        ? styles.incompleteReasonError
                        : styles.incompleteReasonWarning,
                    ];
                    const rowContent = (
                      <>
                        <Text style={styles.incompleteReasonBullet}>
                          <Icon
                            name={item.severity === 'error' ? 'error' : 'warning'}
                            size={16}
                            color={
                              item.severity === 'error'
                                ? colors.destructive
                                : colors.warning
                            }
                          />
                        </Text>
                        <View style={styles.incompleteReasonContent}>
                          <Text
                            style={[
                              styles.incompleteReasonText,
                              item.severity === 'error' &&
                                styles.incompleteReasonTextError,
                            ]}>
                            {item.reason}
                          </Text>
                          {item.hint ? (
                            <Text style={styles.incompleteReasonHint}>
                              {item.hint}
                            </Text>
                          ) : null}
                        </View>
                        {isActionable ? (
                          <Icon
                            name="chevron-right"
                            size={20}
                            color={
                              item.severity === 'error'
                                ? '#991B1B'
                                : '#92400E'
                            }
                          />
                        ) : null}
                      </>
                    );

                    if (isActionable) {
                      return (
                        <TouchableOpacity
                          key={item.id}
                          style={rowStyle}
                          onPress={() => handleIncompleteReasonPress(item)}
                          activeOpacity={0.7}
                          accessibilityRole="button"
                          accessibilityHint={item.hint}
                          accessibilityLabel={item.reason}>
                          {rowContent}
                        </TouchableOpacity>
                      );
                    }

                    return (
                      <View key={item.id} style={rowStyle}>
                        {rowContent}
                      </View>
                    );
                  })}
                </View>

                {requiresIncompleteAcknowledgment && (
                  <TouchableOpacity
                    style={styles.acknowledgeCheckboxRow}
                    onPress={() => setAcknowledgeIncomplete(!acknowledgeIncomplete)}
                  >
                    <View style={[
                      styles.acknowledgeCheckbox,
                      acknowledgeIncomplete && styles.acknowledgeCheckboxChecked
                    ]}>
                      {acknowledgeIncomplete && (
                        <Icon name="check" size={18} color={colors.primaryForeground} />
                      )}
                    </View>
                    <Text style={styles.acknowledgeCheckboxLabel}>
                      I have reviewed the soft warnings above and wish to continue completing this order
                    </Text>
                  </TouchableOpacity>
                )}
              </CardContent>
            </Card>
          )}
        </ScrollView>
      </View>

      <View style={styles.footer}>
        <Button
          title="Back"
          variant="outline"
          size="md"
          onPress={onBack}
        />
        <View style={styles.checklistButtonWrap}>
          <Button
            title="Service Checklist"
            variant="secondary"
            size="md"
            onPress={() => {
              setShowChecklistModal(true);
            }}
          />
          {isChecklistCompleted && (
            <View style={styles.checklistButtonCheckBadge}>
              <Icon
                name="check"
                size={14}
                color={colors.primaryForeground}
              />
            </View>
          )}
        </View>
        <Button
          title={allServiceTypesComplete ? "Acknowledge & Complete Order" : "Acknowledge & Complete Work Order"}
          variant="primary"
          size="md"
          disabled={
            !customerFirstName.trim() ||
            !customerLastName.trim() ||
            !customerSignature ||
            hasHardBlockingErrors ||
            (requiresIncompleteAcknowledgment && !acknowledgeIncomplete)
          }
          onPress={handleCompleteOrder}
        />
      </View>

      <SignatureCaptureModal
        visible={showSignatureModal}
        title="Customer Signature"
        onClose={() => setShowSignatureModal(false)}
        onSave={dataUri => {
          setCustomerSignature(dataUri);
          setShowSignatureModal(false);
        }}
      />
    </View>
  );
};
